;; (add-to-list 'load-path "~/.emacs.d/gdb/")
;; (require 'gdb-ui)
(setq gdb-many-windows 1)
;; (setq gdb-non-stop-setting nil)
;; (setq gdb-use-separate-io-buffer nil)
;; (setq gdb-show-main nil)
;; (setq gud-chdir-before-run nil)
;; (setq gud-tooltip-mode 1)
